export const EVENT_MAP: Record<string, { icon: string; label: string; color: string }> = {
  page_view:              { icon: "👁️", label: "Viewed page",           color: "#8E93A8" },
  idea_viewed:            { icon: "💡", label: "Viewed idea",           color: "#06B6D4" },
  idea_saved:             { icon: "💾", label: "Saved idea",            color: "#10B981" },
  idea_shared:            { icon: "📤", label: "Shared idea",           color: "#8B5CF6" },
  signup_completed:       { icon: "🎉", label: "Signed up",             color: "#F59E0B" },
  login_completed:        { icon: "🔑", label: "Logged in",             color: "#8E93A8" },
  validation_started:     { icon: "🔬", label: "Started validation",    color: "#A855F7" },
  validation_completed:   { icon: "✅", label: "Completed validation",  color: "#10B981" },
  validation_example_clicked: { icon: "💡", label: "Tried example",     color: "#A855F7" },
  validation_voice_used:  { icon: "🎤", label: "Used voice input",      color: "#A855F7" },
  validation_limit_reached: { icon: "🚫", label: "Hit validation limit", color: "#EF4444" },
  blueprint_viewed:       { icon: "📋", label: "Viewed blueprint",      color: "#06B6D4" },
  blueprint_tab_switched: { icon: "📋", label: "Switched blueprint tab", color: "#06B6D4" },
  cta_hero_click:         { icon: "🚀", label: "Clicked hero CTA",      color: "#F59E0B" },
  cta_explore_problems:   { icon: "🔍", label: "Clicked explore",       color: "#06B6D4" },
  cta_validate_idea:      { icon: "⚡", label: "Clicked validate CTA",  color: "#A855F7" },
  cta_get_started:        { icon: "▶️", label: "Clicked get started",   color: "#10B981" },
  cta_claim_pro:          { icon: "⭐", label: "Clicked claim Pro",     color: "#8B5CF6" },
  waitlist_banner_submit: { icon: "📧", label: "Joined waitlist",       color: "#EF4444" },
  waitlist_modal_opened:  { icon: "📧", label: "Opened waitlist modal", color: "#F59E0B" },
  waitlist_joined:        { icon: "🎉", label: "Joined Pro waitlist",   color: "#10B981" },
  quiz_started:           { icon: "🧬", label: "Started onboarding",    color: "#A855F7" },
  quiz_completed:         { icon: "🎯", label: "Completed onboarding",  color: "#10B981" },
  onboarding_step_completed: { icon: "📝", label: "Onboarding step",    color: "#A855F7" },
  onboarding_skipped:     { icon: "⏭️", label: "Skipped onboarding",   color: "#F59E0B" },
  time_on_page:           { icon: "⏱️", label: "Time on page",          color: "#64748B" },
  signal_viewed:          { icon: "📡", label: "Viewed signal",         color: "#06B6D4" },
  signal_platform_filtered: { icon: "🔍", label: "Filtered signals",   color: "#06B6D4" },
  signal_expanded:        { icon: "📡", label: "Expanded signal",       color: "#06B6D4" },
  signal_external_clicked: { icon: "🔗", label: "Clicked signal link",  color: "#06B6D4" },
  use_case_viewed:        { icon: "💼", label: "Viewed use case",       color: "#8B5CF6" },
  usecase_searched:       { icon: "🔍", label: "Searched use cases",    color: "#8B5CF6" },
  usecase_filtered:       { icon: "🔍", label: "Filtered use cases",    color: "#8B5CF6" },
  usecase_upgrade_clicked: { icon: "🔒", label: "Hit use case paywall", color: "#F59E0B" },
  feed_sort_changed:      { icon: "🔄", label: "Changed feed sort",    color: "#8E93A8" },
  feed_category_filtered: { icon: "🏷️", label: "Filtered feed",        color: "#8E93A8" },
  feed_search_performed:  { icon: "🔍", label: "Searched feed",         color: "#8E93A8" },
  feed_load_more:         { icon: "📜", label: "Loaded more ideas",     color: "#8E93A8" },
  saved_idea_opened:      { icon: "💾", label: "Opened saved idea",     color: "#10B981" },
  settings_profile_updated: { icon: "👤", label: "Updated profile",     color: "#8E93A8" },
  settings_notification_toggled: { icon: "🔔", label: "Toggled notification", color: "#8E93A8" },
  settings_signout:       { icon: "🚪", label: "Signed out",            color: "#8E93A8" },
  share_modal_opened:     { icon: "📤", label: "Opened share modal",    color: "#8B5CF6" },
  leaderboard_viewed:     { icon: "🏆", label: "Viewed leaderboard",    color: "#F59E0B" },
  session_start:          { icon: "🟢", label: "Session started",       color: "#10B981" },
  error_js:               { icon: "🐛", label: "JS Error",              color: "#EF4444" },
  error_api:              { icon: "⚠️", label: "API Error",             color: "#EF4444" },
  rage_click:             { icon: "😤", label: "Rage clicked",          color: "#EF4444" },
  dead_click:             { icon: "👆", label: "Dead click",             color: "#F59E0B" },
};

export const FEATURE_COLORS: Record<string, string> = {
  validation: "#A855F7",
  blueprint: "#06B6D4",
  competitors: "#F59E0B",
  matching: "#10B981",
};

export const FEATURE_LABELS: Record<string, string> = {
  validation: "Validation",
  blueprint: "Blueprint",
  competitors: "Competitors",
  matching: "Matching",
};

export const getEventDisplay = (eventName: string) =>
  EVENT_MAP[eventName] || { icon: "\u2022", label: eventName, color: "#8E93A8" };
